#
# Site configuration flags
# Jekyll (http://jekyllrb.com/)
#

# Site info
name: Inspire &middot; Junior-Entreprise de Télécom Saint-Étienne
description: Inspire &middot; Junior-Entreprise de Télécom Saint-Étienne
version: 1.0.0
repository: Inspire-Telecom/site

# Used for Sitemap.xml and your RSS feed
url: https://next.inspire-telecom.com
baseurl: ""

# Used for SEO
author: Inspire
logo: /assets/icon/favicon.png

# Front Tools
google_analytics: UA-78299187-1

# Engines
permalink: /:title/
paginate: 10
paginate_path: /page/:num
sass:
  style: :compressed

# Collections
collections:
  sections:
    output: false

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
